Make OutputConstructorAttribute optional
pulumi/pulumi-dotnet pull request #439
Opened 2024-12-30 10:45 UTC by rosieks

This PR address issue #438 
It changes behavior of converter in a way that if there is no `OutputConstructorAttribute` and at the same time there is single public constructor then it tries to use it.

2025-01-06 01:49 UTC, brandonpollack23 requested changes

2025-01-06 01:49 UTC, brandonpollack23 commented on sdk/Pulumi/Serialization/Converter.cs
> +            return outputConstructor;
I personally prefer the early return style the other way with explicit null return:

```csharp
if (outputConstructor != null)
{
  return outputConstructor;
}

var publicConstructors = constructors.Where(x => x.IsPublic).ToArray();
if (publicConstructors.Length == 1)
{
  return publicConstructors[0];
}

return null;
```

2025-01-06 10:50 UTC, rosieks commented on sdk/Pulumi/Serialization/Converter.cs
> +            return outputConstructor;
Changed

2025-01-07 01:45 UTC, brandonpollack23 approved these changes

2025-02-25 08:45 UTC, Frassle commented
Hi @rosieks, if you rebase/merge main into this I think it will retrigger the CI checks and we can get this merged.

2025-02-27 08:48 UTC, merged